app:
  kafka:
    bootstrapServer: "10.10.1.131:9092"
    securityProtocol: "PLAINTEXT"
    schemaRegistryUrl: "http://10.10.1.131:8081/"
    avroSerializableClasses:
      - "io.bekk.publisher.BekkbookStatusMessage"
server:
  port: ${PORT:3000}
